/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 11 15:05:25 GMT 2026
 */

package ar.edu.unrc.game2048;

import org.junit.Test;
import static org.junit.Assert.*;
import ar.edu.unrc.game2048.Board;
import ar.edu.unrc.game2048.Cell;
import ar.edu.unrc.game2048.strategy.LeftMoveStrategy;
import ar.edu.unrc.game2048.strategy.MoveStrategy;
import ar.edu.unrc.game2048.strategy.UpMoveStrategy;
import java.util.Set;

public class Board_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Board board0 = new Board();
      board0.moveRight();
      UpMoveStrategy upMoveStrategy0 = new UpMoveStrategy();
      boolean boolean0 = board0.move(upMoveStrategy0);
      assertEquals(4, board0.getScore());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-1449), (-2000));
      String string0 = board_Position0.toString();
      assertEquals("(-1449, -2000)", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Board board0 = new Board();
      int int0 = board0.getScore();
      assertEquals(4, board0.getSize());
      assertEquals(0, int0);
      assertFalse(board0.isWinningBoard());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Board board0 = new Board(2);
      boolean boolean0 = board0.moveLeft();
      assertFalse(boolean0);
      assertFalse(board0.isWinningBoard());
      assertEquals(2, board0.getSize());
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((-1604));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -1604
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell(4, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, 4) is out of bounds for board size 4
         //
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Board board0 = new Board();
      UpMoveStrategy upMoveStrategy0 = new UpMoveStrategy();
      // Undeclared exception!
      try { 
        upMoveStrategy0.extractLine(board0, (-3118));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, -3118) is out of bounds for board size 4
         //
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Board board0 = new Board(1);
      // Undeclared exception!
      try { 
        board0.getCell(0, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 4) is out of bounds for board size 1
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Board board0 = new Board(2);
      boolean boolean0 = board0.hasEmptyCells();
      assertEquals(0, board0.getScore());
      assertTrue(boolean0);
      assertEquals(2, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Board board0 = new Board(2);
      board0.moveRight();
      board0.moveDown();
      board0.moveLeft();
      boolean boolean0 = board0.isLosingBoard();
      assertEquals(4, board0.getScore());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.isLosingBoard();
      assertEquals(4, board0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Board board0 = new Board(2);
      board0.moveRight();
      board0.moveRight();
      board0.moveDown();
      boolean boolean0 = board0.isLosingBoard();
      assertEquals(4, board0.getScore());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Board board0 = new Board(2);
      board0.moveRight();
      board0.moveDown();
      board0.moveUp();
      boolean boolean0 = board0.isLosingBoard();
      assertEquals(4, board0.getScore());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.isFull();
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Board board0 = new Board(1);
      boolean boolean0 = board0.isFull();
      assertTrue(boolean0);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.equals((Object) null);
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Board board0 = new Board();
      board0.equals("ar.edu.unrc.game2048.strategy.RightMoveStrategy");
      assertEquals(0, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Board board0 = new Board();
      String string0 = board0.toString();
      assertEquals("Score: 0\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|    2|    2|     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-1449), (-2000));
      boolean boolean0 = board_Position0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals((-1449), board_Position0.row);
      assertEquals((-2000), board_Position0.col);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-1449), (-2000));
      boolean boolean0 = board_Position0.equals(board_Position0);
      assertEquals((-2000), board_Position0.col);
      assertEquals((-1449), board_Position0.row);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-1449), (-2000));
      Board.Position board_Position1 = new Board.Position(1, 4);
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertEquals(1, board_Position1.row);
      assertFalse(boolean0);
      assertEquals(4, board_Position1.col);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-1449), (-2000));
      Object object0 = new Object();
      boolean boolean0 = board_Position0.equals(object0);
      assertFalse(boolean0);
      assertEquals((-1449), board_Position0.row);
      assertEquals((-2000), board_Position0.col);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-404), 793);
      Board.Position board_Position1 = new Board.Position((-404), (-404));
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertFalse(board_Position1.equals((Object)board_Position0));
      assertFalse(boolean0);
      assertEquals((-404), board_Position1.row);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Board board0 = new Board();
      int int0 = board0.getSize();
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(board0);
      boolean boolean0 = board0.equals(board1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = new Cell(0);
      board0.setCell(0, 0, cell0);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Board board0 = new Board();
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertFalse(board0.isWinningBoard());
      assertEquals(14, set0.size());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Board board0 = new Board(1);
      boolean boolean0 = board0.hasEmptyCells();
      assertFalse(boolean0);
      assertEquals(1, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Board board0 = new Board();
      UpMoveStrategy upMoveStrategy0 = new UpMoveStrategy();
      boolean boolean0 = board0.move(upMoveStrategy0);
      assertFalse(board0.isWinningBoard());
      assertTrue(boolean0);
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Board board0 = new Board(1);
      UpMoveStrategy upMoveStrategy0 = new UpMoveStrategy();
      boolean boolean0 = board0.move(upMoveStrategy0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Board board0 = new Board();
      board0.equals(board0);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(board0);
      LeftMoveStrategy leftMoveStrategy0 = new LeftMoveStrategy();
      board1.move(leftMoveStrategy0);
      boolean boolean0 = board0.equals(board1);
      assertEquals(4, board1.getScore());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Board board0 = new Board(653);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((Board) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.move((MoveStrategy) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = new Cell(0);
      // Undeclared exception!
      try { 
        board0.setCell((-2000), (-1449), cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-2000, -1449) is out of bounds for board size 4
         //
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = board0.getCell(1, 1);
      assertEquals(4, board0.getSize());
      assertEquals("2", cell0.toString());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = board0.getCell(0, 0);
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(".", cell0.toString());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Board board0 = new Board(1);
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertFalse(board0.isWinningBoard());
      assertEquals(0, set0.size());
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Board board0 = new Board();
      assertEquals(0, board0.getScore());
      
      board0.moveLeft();
      int int0 = board0.getScore();
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Board board0 = new Board(1);
      boolean boolean0 = board0.moveDown();
      assertEquals(1, board0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Board board0 = new Board(1);
      boolean boolean0 = board0.moveRight();
      assertEquals(1, board0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Board board0 = new Board(1);
      boolean boolean0 = board0.moveUp();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell(2048, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2048, 4) is out of bounds for board size 4
         //
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Board board0 = new Board();
      UpMoveStrategy upMoveStrategy0 = new UpMoveStrategy();
      // Undeclared exception!
      try { 
        upMoveStrategy0.extractLine(board0, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 4) is out of bounds for board size 4
         //
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Board board0 = new Board(2);
      boolean boolean0 = board0.isWinningBoard();
      assertEquals(2, board0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Board board0 = new Board(1);
      board0.hashCode();
      assertFalse(board0.isWinningBoard());
      assertEquals(1, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Board board0 = new Board(1);
      String string0 = board0.toString();
      assertEquals("Score: 0\n+-----+\n|    2|\n+-----+\n", string0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(1700, 0);
      Board.Position board_Position1 = new Board.Position((-622), 1700);
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertEquals((-622), board_Position1.row);
      assertEquals(1700, board_Position1.col);
      assertFalse(boolean0);
  }
}
