/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 11 18:47:44 GMT 2026
 */

package ar.edu.unrc.game2048;

import org.junit.Test;
import static org.junit.Assert.*;
import ar.edu.unrc.game2048.Board;
import ar.edu.unrc.game2048.Cell;
import ar.edu.unrc.game2048.strategy.DownMoveStrategy;
import ar.edu.unrc.game2048.strategy.LeftMoveStrategy;
import ar.edu.unrc.game2048.strategy.MoveStrategy;
import ar.edu.unrc.game2048.strategy.RightMoveStrategy;
import ar.edu.unrc.game2048.strategy.UpMoveStrategy;
import java.util.List;
import java.util.Set;
import org.junit.Ignore;

public class Board_ESTest {

  // FLAKY: depende de las fichas aleatorias.
  @Ignore("Flaky: tablero aleatorio")
  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Board board0 = new Board();
      board0.getEmptyPositions();
      board0.moveLeft();
      Cell cell0 = new Cell(0);
      board0.setCell(2, 2, cell0);
      board0.isFull();
      board0.isFull();
      board0.isWinningBoard();
      board0.hashCode();
      board0.isLosingBoard();
      boolean boolean0 = board0.hasEmptyCells();
      assertEquals(4, board0.getScore());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Board board0 = new Board();
      board0.moveUp();
      board0.toString();
      Board.Position board_Position0 = new Board.Position((-1), (-882));
      board0.toString();
      board0.isLosingBoard();
      board_Position0.toString();
      Board.Position board_Position1 = new Board.Position(2048, (-2285));
      board0.toString();
      board_Position1.toString();
      board_Position1.toString();
      board0.getEmptyPositions();
      board_Position0.equals(board_Position1);
      board0.toString();
      board0.moveRight();
      board0.getScore();
      board0.repOK();
      board_Position0.equals(board_Position1);
      board0.moveRight();
      Cell cell0 = Cell.EMPTY;
      // Undeclared exception!
      try { 
        board0.setCell((-1894), 96, cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-1894, 96) is out of bounds for board size 4
         //
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Board board0 = new Board();
      board0.isLosingBoard();
      board0.moveLeft();
      board0.isWinningBoard();
      String string0 = "BqCH";
      board0.moveLeft();
      board0.hasEmptyCells();
      LeftMoveStrategy leftMoveStrategy0 = new LeftMoveStrategy();
      board0.move(leftMoveStrategy0);
      board0.moveLeft();
      board0.hashCode();
      board0.moveDown();
      board0.moveRight();
      board0.moveUp();
      int int0 = 1;
      Cell cell0 = new Cell(2048);
      // Undeclared exception!
      try { 
        board0.setCell((-2827), 1, cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-2827, 1) is out of bounds for board size 4
         //
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((-3253));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -3253
         //
      }
  }

  // FLAKY: depende de las fichas aleatorias.
  @Ignore("Flaky: tablero aleatorio")
  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Board board0 = new Board();
      board0.moveDown();
      boolean boolean0 = board0.moveUp();
      boolean boolean1 = board0.isLosingBoard();
      boolean boolean2 = board0.hasEmptyCells();
      assertTrue(boolean2 == boolean0);
      
      Board.Position board_Position0 = new Board.Position(558, 4);
      boolean boolean3 = board_Position0.equals(board0);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(boolean3 == boolean1);
      assertFalse(board0.isWinningBoard());
      assertFalse(boolean3);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Board board0 = new Board(1);
      board0.toString();
      board0.moveRight();
      board0.isFull();
      board0.moveLeft();
      board0.moveUp();
      board0.moveUp();
      board0.getEmptyPositions();
      board0.hasEmptyCells();
      board0.moveLeft();
      board0.hashCode();
      board0.moveUp();
      board0.isLosingBoard();
      board0.hashCode();
      board0.moveDown();
      board0.moveUp();
      board0.isFull();
      // Undeclared exception!
      try { 
        board0.getCell(0, 1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 1) is out of bounds for board size 1
         //
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(10, 4);
      board_Position0.toString();
      board_Position0.toString();
      Board.Position board_Position1 = new Board.Position(10, 16);
      board_Position1.toString();
      board_Position1.toString();
      board_Position1.toString();
      board_Position0.equals(board_Position1);
      Board board0 = new Board();
      board0.getScore();
      board0.moveRight();
      board0.isWinningBoard();
      board0.getSize();
      // Undeclared exception!
      try { 
        board0.getCell(10, 10);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (10, 10) is out of bounds for board size 4
         //
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Board board0 = new Board();
      LeftMoveStrategy leftMoveStrategy0 = new LeftMoveStrategy();
      Board board1 = new Board(board0);
      int int0 = 286;
      RightMoveStrategy rightMoveStrategy0 = new RightMoveStrategy();
      // Undeclared exception!
      try { 
        rightMoveStrategy0.extractLine(board1, 1853);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (1853, 3) is out of bounds for board size 4
         //
      }
  }

  // FLAKY: depende de las fichas aleatorias.
  @Ignore("Flaky: tablero aleatorio")
  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Board board0 = new Board();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(board0);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      boolean boolean0 = board0.moveLeft();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(boolean0);
      assertEquals(4, board0.getSize());
      assertEquals(4, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      boolean boolean1 = board0.moveRight();
      assertTrue(boolean1 == boolean0);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(boolean1);
      assertEquals(4, board0.getSize());
      assertEquals(4, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      boolean boolean2 = board0.hasEmptyCells();
      assertTrue(boolean2 == boolean1);
      assertTrue(boolean2 == boolean0);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(boolean2);
      assertEquals(4, board0.getSize());
      assertEquals(4, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      boolean boolean3 = board0.moveUp();
      assertTrue(boolean3 == boolean1);
      assertTrue(boolean3 == boolean0);
      assertTrue(boolean3 == boolean2);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(boolean3);
      assertEquals(4, board0.getSize());
      assertEquals(4, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      boolean boolean4 = board0.moveLeft();
      assertTrue(boolean4 == boolean3);
      assertTrue(boolean4 == boolean2);
      assertTrue(boolean4 == boolean0);
      assertTrue(boolean4 == boolean1);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(boolean4);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(8, board0.getScore());
      
      Cell cell0 = Cell.EMPTY;
      board0.equals(cell0);
      assertEquals(8, board0.getScore());
  }

  // FLAKY: depende de las fichas aleatorias.
  @Ignore("Flaky: tablero aleatorio")
  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, 4);
      board_Position0.toString();
      Board.Position board_Position1 = new Board.Position(0, 1);
      board_Position1.toString();
      String string0 = board_Position1.toString();
      assertEquals("(0, 1)", string0);
      
      board_Position0.equals(board_Position1);
      Board board0 = new Board();
      board0.getScore();
      board0.moveRight();
      board0.isWinningBoard();
      board0.getSize();
      assertEquals(4, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell(0, (-1));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, -1) is out of bounds for board size 4
         //
      }
  }

  // FLAKY: depende de las fichas aleatorias.
  @Ignore("Flaky: tablero aleatorio")
  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Board board0 = new Board();
      board0.toString();
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertEquals(14, set0.size());
      
      String string0 = board0.toString();
      assertEquals("Score: 0\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|    2|    2|     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: 0
         //
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Board.Direction.values();
      Board board0 = new Board();
      board0.hasEmptyCells();
      board0.moveRight();
      board0.isFull();
      board0.toString();
      int int0 = 1731;
      board0.moveDown();
      Cell cell0 = Cell.EMPTY;
      // Undeclared exception!
      try { 
        board0.setCell(2, 1731, cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2, 1731) is out of bounds for board size 4
         //
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Board board0 = new Board();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(board0);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      
      boolean boolean0 = board0.hasEmptyCells();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertTrue(boolean0);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      
      Board board1 = new Board(board0);
      assertTrue(board1.equals((Object)board0));
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(board1);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertTrue(board1.repOK());
      assertEquals(4, board1.getSize());
      assertFalse(board1.isWinningBoard());
      assertEquals(0, board1.getScore());
      
      int int0 = (-2517);
      // Undeclared exception!
      try { 
        board1.getCell(2048, 0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2048, 0) is out of bounds for board size 4
         //
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Board board0 = new Board(622);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Board board0 = null;
      Board board1 = null;
      try {
        board1 = new Board((Board) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      int int0 = (-2904);
      Board.Position board_Position0 = new Board.Position((-2904), (-2904));
      assertEquals((-2904), board_Position0.row);
      assertEquals((-2904), board_Position0.col);
      assertNotNull(board_Position0);
      
      String string0 = board_Position0.toString();
      assertEquals((-2904), board_Position0.row);
      assertEquals((-2904), board_Position0.col);
      assertNotNull(string0);
      assertEquals("(-2904, -2904)", string0);
      
      String string1 = board_Position0.toString();
      assertTrue(string1.equals((Object)string0));
      assertEquals((-2904), board_Position0.row);
      assertEquals((-2904), board_Position0.col);
      assertNotNull(string1);
      assertEquals("(-2904, -2904)", string1);
      
      String string2 = board_Position0.toString();
      assertTrue(string2.equals((Object)string1));
      assertTrue(string2.equals((Object)string0));
      assertEquals((-2904), board_Position0.row);
      assertEquals((-2904), board_Position0.col);
      assertNotNull(string2);
      assertEquals("(-2904, -2904)", string2);
      
      String string3 = board_Position0.toString();
      assertTrue(string3.equals((Object)string0));
      assertTrue(string3.equals((Object)string1));
      assertTrue(string3.equals((Object)string2));
      assertEquals((-2904), board_Position0.row);
      assertEquals((-2904), board_Position0.col);
      assertNotNull(string3);
      assertEquals("(-2904, -2904)", string3);
      
      String string4 = board_Position0.toString();
      assertTrue(string4.equals((Object)string0));
      assertTrue(string4.equals((Object)string3));
      assertTrue(string4.equals((Object)string1));
      assertTrue(string4.equals((Object)string2));
      assertEquals((-2904), board_Position0.row);
      assertEquals((-2904), board_Position0.col);
      assertNotNull(string4);
      assertEquals("(-2904, -2904)", string4);
      
      String string5 = board_Position0.toString();
      assertTrue(string5.equals((Object)string4));
      assertTrue(string5.equals((Object)string2));
      assertTrue(string5.equals((Object)string0));
      assertTrue(string5.equals((Object)string1));
      assertTrue(string5.equals((Object)string3));
      assertEquals((-2904), board_Position0.row);
      assertEquals((-2904), board_Position0.col);
      assertNotNull(string5);
      assertEquals("(-2904, -2904)", string5);
      
      Board board0 = new Board(34);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(board0);
      assertEquals(34, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      // Undeclared exception!
      board0.moveLeft();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Board board0 = new Board(1);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(board0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      
      // Undeclared exception!
      try { 
        board0.getCell((-2702), 1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-2702, 1) is out of bounds for board size 1
         //
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Board board0 = new Board(1);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(board0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      
      boolean boolean0 = board0.moveDown();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(boolean0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
  }

  // FLAKY: depende de las fichas aleatorias.
  @Ignore("Flaky: tablero aleatorio")
  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Board board0 = new Board(2);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(board0);
      assertEquals(2, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      boolean boolean0 = board0.isLosingBoard();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertFalse(boolean0);
      assertEquals(2, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      boolean boolean1 = board0.moveDown();
      assertFalse(boolean1 == boolean0);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(boolean1);
      assertEquals(2, board0.getSize());
      assertEquals(4, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      String string0 = board0.toString();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(string0);
      assertEquals("Score: 4\n+-----+-----+\n|     |     |\n+-----+-----+\n|    4|    2|\n+-----+-----+\n", string0);
      assertEquals(2, board0.getSize());
      assertEquals(4, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      boolean boolean2 = board0.repOK();
      assertTrue(boolean2 == boolean1);
      assertFalse(boolean2 == boolean0);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(boolean2);
      assertEquals(2, board0.getSize());
      assertEquals(4, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(set0);
      assertEquals(2, board0.getSize());
      assertEquals(4, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertFalse(set0.isEmpty());
      assertEquals(2, set0.size());
      
      DownMoveStrategy downMoveStrategy0 = new DownMoveStrategy();
      assertNotNull(downMoveStrategy0);
      
      // Undeclared exception!
      try { 
        downMoveStrategy0.extractLine(board0, 2048);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (1, 2048) is out of bounds for board size 2
         //
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Board board0 = new Board(3);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(board0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(3, board0.getSize());
      
      boolean boolean0 = board0.hasEmptyCells();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(boolean0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(3, board0.getSize());
      
      boolean boolean1 = board0.isLosingBoard();
      assertFalse(boolean1 == boolean0);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertFalse(boolean1);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(3, board0.getSize());
      
      boolean boolean2 = board0.isLosingBoard();
      assertFalse(boolean2 == boolean0);
      assertTrue(boolean2 == boolean1);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertFalse(boolean2);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(3, board0.getSize());
      
      boolean boolean3 = board0.isWinningBoard();
      assertFalse(boolean3 == boolean0);
      assertTrue(boolean3 == boolean2);
      assertTrue(boolean3 == boolean1);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertFalse(boolean3);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(3, board0.getSize());
      
      // Undeclared exception!
      try { 
        board0.setCell(3, 3, (Cell) null);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (3, 3) is out of bounds for board size 3
         //
      }
  }

  // FLAKY: depende de las fichas aleatorias.
  @Ignore("Flaky: tablero aleatorio")
  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Board board0 = new Board();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(board0);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      
      boolean boolean0 = board0.moveRight();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertTrue(boolean0);
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getScore());
      
      boolean boolean1 = board0.moveRight();
      assertFalse(boolean1 == boolean0);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(boolean1);
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getScore());
      
      boolean boolean2 = board0.moveDown();
      assertFalse(boolean2 == boolean1);
      assertTrue(boolean2 == boolean0);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertTrue(boolean2);
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getScore());
      
      // Undeclared exception!
      try { 
        board0.getCell(1652, 1652);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (1652, 1652) is out of bounds for board size 4
         //
      }
  }

  // FLAKY: depende de las fichas aleatorias.
  @Ignore("Flaky: tablero aleatorio")
  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Board board0 = new Board(3);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(board0);
      assertEquals(0, board0.getScore());
      assertEquals(3, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      UpMoveStrategy upMoveStrategy0 = new UpMoveStrategy();
      assertNotNull(upMoveStrategy0);
      
      boolean boolean0 = board0.move(upMoveStrategy0);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(boolean0);
      assertEquals(3, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Board board0 = new Board();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(board0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      
      DownMoveStrategy downMoveStrategy0 = new DownMoveStrategy();
      assertNotNull(downMoveStrategy0);
      
      boolean boolean0 = board0.move(downMoveStrategy0);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertTrue(boolean0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      
      Board board1 = new Board(board0);
      assertTrue(board1.equals((Object)board0));
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(board1);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board1.repOK());
      assertEquals(0, board1.getScore());
      assertEquals(4, board1.getSize());
      assertFalse(board1.isWinningBoard());
  }

  // FLAKY: depende de las fichas aleatorias.
  @Ignore("Flaky: tablero aleatorio")
  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Board board0 = new Board();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(board0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      
      UpMoveStrategy upMoveStrategy0 = new UpMoveStrategy();
      assertNotNull(upMoveStrategy0);
      
      boolean boolean0 = board0.move(upMoveStrategy0);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertTrue(boolean0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      
      boolean boolean1 = board0.isLosingBoard();
      assertFalse(boolean1 == boolean0);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(boolean1);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      
      board0.hashCode();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      
      int int0 = board0.getSize();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(4, int0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      
      // Undeclared exception!
      try { 
        Board.Direction.valueOf("qQXmxY~f;5=PL&K`GMA");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant ar.edu.unrc.game2048.Board.Direction.qQXmxY~f;5=PL&K`GMA
         //
      }
  }

  // FLAKY: depende de las fichas aleatorias.
  @Ignore("Flaky: tablero aleatorio")
  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, 0);
      assertEquals(0, board_Position0.col);
      assertEquals(0, board_Position0.row);
      assertNotNull(board_Position0);
      
      Board board0 = new Board();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(board0);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      
      String string0 = board0.toString();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(string0);
      assertEquals("Score: 0\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|    2|    2|     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n", string0);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      
      boolean boolean0 = board0.moveDown();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertTrue(boolean0);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      
      String string1 = board_Position0.toString();
      assertFalse(string1.equals((Object)string0));
      assertEquals(0, board_Position0.col);
      assertEquals(0, board_Position0.row);
      assertNotNull(string1);
      assertEquals("(0, 0)", string1);
      
      boolean boolean1 = board0.moveRight();
      assertTrue(boolean1 == boolean0);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertTrue(boolean1);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getScore());
      assertEquals(4, board0.getSize());
      
      int int0 = board0.getScore();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(4, int0);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getScore());
      assertEquals(4, board0.getSize());
      
      Cell cell0 = new Cell(0);
      assertNotNull(cell0);
      assertTrue(cell0.repOK());
      assertTrue(cell0.isEmpty());
      assertEquals(".", cell0.toString());
      assertEquals(0, cell0.getValue());
      
      boolean boolean2 = board_Position0.equals(cell0);
      assertFalse(boolean2 == boolean1);
      assertFalse(boolean2 == boolean0);
      assertEquals(0, board_Position0.col);
      assertEquals(0, board_Position0.row);
      assertFalse(boolean2);
      assertTrue(cell0.repOK());
      assertTrue(cell0.isEmpty());
      assertEquals(".", cell0.toString());
      assertEquals(0, cell0.getValue());
      
      boolean boolean3 = board0.isWinningBoard();
      assertFalse(boolean3 == boolean1);
      assertFalse(boolean3 == boolean0);
      assertTrue(boolean3 == boolean2);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(boolean3);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getScore());
      assertEquals(4, board0.getSize());
      
      // Undeclared exception!
      try { 
        Board.Direction.valueOf((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Name is null
         //
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      int int0 = 1;
      Board board0 = new Board(1);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(board0);
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(1, board0.getSize());
      
      int int1 = 2646;
      // Undeclared exception!
      try { 
        board0.move((MoveStrategy) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Board board0 = new Board();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(board0);
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(set0);
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertFalse(set0.isEmpty());
      assertEquals(14, set0.size());
      
      Board.Position board_Position0 = new Board.Position(4, 0);
      assertEquals(0, board_Position0.col);
      assertEquals(4, board_Position0.row);
      assertNotNull(board_Position0);
      
      boolean boolean0 = board_Position0.equals((Object) null);
      assertEquals(0, board_Position0.col);
      assertEquals(4, board_Position0.row);
      assertFalse(boolean0);
  }

  // FLAKY: depende de las fichas aleatorias.
  @Ignore("Flaky: tablero aleatorio")
  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Board board0 = new Board(2);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(board0);
      assertFalse(board0.isWinningBoard());
      assertEquals(2, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      
      boolean boolean0 = board0.isLosingBoard();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(boolean0);
      assertFalse(board0.isWinningBoard());
      assertEquals(2, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      
      boolean boolean1 = board0.moveDown();
      assertFalse(boolean1 == boolean0);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertTrue(boolean1);
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getScore());
      assertEquals(2, board0.getSize());
      assertTrue(board0.repOK());
      
      String string0 = board0.toString();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(string0);
      assertEquals("Score: 4\n+-----+-----+\n|     |     |\n+-----+-----+\n|    4|    2|\n+-----+-----+\n", string0);
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getScore());
      assertEquals(2, board0.getSize());
      assertTrue(board0.repOK());
      
      boolean boolean2 = board0.moveLeft();
      assertTrue(boolean2 == boolean0);
      assertFalse(boolean2 == boolean1);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(boolean2);
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getScore());
      assertEquals(2, board0.getSize());
      assertTrue(board0.repOK());
      
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(set0);
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getScore());
      assertEquals(2, board0.getSize());
      assertTrue(board0.repOK());
      assertEquals(2, set0.size());
      assertFalse(set0.isEmpty());
      
      DownMoveStrategy downMoveStrategy0 = new DownMoveStrategy();
      assertNotNull(downMoveStrategy0);
      
      // Undeclared exception!
      try { 
        downMoveStrategy0.extractLine(board0, 2048);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (1, 2048) is out of bounds for board size 2
         //
      }
  }

  // FLAKY: depende de las fichas aleatorias.
  @Ignore("Flaky: tablero aleatorio")
  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Board board0 = new Board();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(board0);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      boolean boolean0 = board0.moveDown();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(boolean0);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      int int0 = board0.getScore();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(0, int0);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      Cell cell0 = board0.getCell(0, 0);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(cell0);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(0, cell0.getValue());
      assertTrue(cell0.repOK());
      assertTrue(cell0.isEmpty());
      assertEquals(".", cell0.toString());
      
      // Undeclared exception!
      try { 
        board0.getCell((-2379), 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-2379, 4) is out of bounds for board size 4
         //
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, 0);
      assertEquals(0, board_Position0.row);
      assertEquals(0, board_Position0.col);
      assertNotNull(board_Position0);
      
      String string0 = board_Position0.toString();
      assertEquals(0, board_Position0.row);
      assertEquals(0, board_Position0.col);
      assertNotNull(string0);
      assertEquals("(0, 0)", string0);
      
      boolean boolean0 = board_Position0.equals((Object) null);
      assertEquals(0, board_Position0.row);
      assertEquals(0, board_Position0.col);
      assertFalse(boolean0);
      
      Board board0 = new Board();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(board0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      
      boolean boolean1 = board0.isLosingBoard();
      assertTrue(boolean1 == boolean0);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(boolean1);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      
      boolean boolean2 = board0.equals(board_Position0);
      assertTrue(boolean2 == boolean1);
      assertTrue(boolean2 == boolean0);
      assertEquals(0, board_Position0.row);
      assertEquals(0, board_Position0.col);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(boolean2);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Board board0 = new Board();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(board0);
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      
      Board board1 = new Board(board0);
      assertTrue(board1.equals((Object)board0));
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(board1);
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertTrue(board1.repOK());
      assertEquals(4, board1.getSize());
      assertFalse(board1.isWinningBoard());
      assertEquals(0, board1.getScore());
      
      boolean boolean0 = board1.moveUp();
      assertNotSame(board0, board1);
      assertNotSame(board1, board0);
      assertFalse(board0.equals((Object)board1));
      assertFalse(board1.equals((Object)board0));
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(boolean0);
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertTrue(board1.repOK());
      assertEquals(4, board1.getSize());
      assertFalse(board1.isWinningBoard());
      assertEquals(0, board1.getScore());
      
      UpMoveStrategy upMoveStrategy0 = new UpMoveStrategy();
      assertNotNull(upMoveStrategy0);
      
      // Undeclared exception!
      try { 
        upMoveStrategy0.extractLine(board0, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 4) is out of bounds for board size 4
         //
      }
  }

  // FLAKY: depende de las fichas aleatorias.
  @Ignore("Flaky: tablero aleatorio")
  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Board board0 = new Board();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(board0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      
      boolean boolean0 = board0.moveDown();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertTrue(boolean0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      
      int int0 = 2;
      Cell cell0 = board0.getCell(2, 2);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(cell0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(cell0.repOK());
      assertFalse(cell0.isEmpty());
      assertEquals(2, cell0.getValue());
      assertEquals("2", cell0.toString());
      
      Cell cell1 = board0.getCell(2, 2);
      assertSame(cell1, cell0);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(cell1);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertFalse(cell1.isEmpty());
      assertEquals(2, cell1.getValue());
      assertEquals("2", cell1.toString());
      assertTrue(cell1.repOK());
      
      Cell cell2 = Cell.EMPTY;
      assertNotSame(cell2, cell0);
      assertNotSame(cell2, cell1);
      assertFalse(cell2.equals((Object)cell0));
      assertFalse(cell2.equals((Object)cell1));
      assertNotNull(cell2);
      assertTrue(cell2.isEmpty());
      assertEquals(".", cell2.toString());
      assertTrue(cell2.repOK());
      assertEquals(0, cell2.getValue());
      
      // Undeclared exception!
      try { 
        cell1.mergeWith(cell2);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot merge cells: 2 and .
         //
      }
  }

  // FLAKY: depende del valor aleatorio de la ficha.
  @Ignore("Flaky: valor aleatorio")
  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Board board0 = new Board(1);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(board0);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertTrue(board0.repOK());
      
      String string0 = board0.toString();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(string0);
      assertEquals("Score: 0\n+-----+\n|    2|\n+-----+\n", string0);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertTrue(board0.repOK());
      
      boolean boolean0 = board0.moveRight();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(boolean0);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertTrue(board0.repOK());
      
      boolean boolean1 = board0.isFull();
      assertFalse(boolean1 == boolean0);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertTrue(boolean1);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertTrue(board0.repOK());
      
      boolean boolean2 = board0.moveLeft();
      assertFalse(boolean2 == boolean1);
      assertTrue(boolean2 == boolean0);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(boolean2);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertTrue(board0.repOK());
      
      boolean boolean3 = board0.moveUp();
      assertTrue(boolean3 == boolean0);
      assertFalse(boolean3 == boolean1);
      assertTrue(boolean3 == boolean2);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(boolean3);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertTrue(board0.repOK());
      
      boolean boolean4 = board0.moveUp();
      assertTrue(boolean4 == boolean0);
      assertFalse(boolean4 == boolean1);
      assertTrue(boolean4 == boolean3);
      assertTrue(boolean4 == boolean2);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(boolean4);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertTrue(board0.repOK());
      
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(set0);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertTrue(board0.repOK());
      assertEquals(0, set0.size());
      assertTrue(set0.isEmpty());
      
      boolean boolean5 = board0.hasEmptyCells();
      assertTrue(boolean5 == boolean0);
      assertTrue(boolean5 == boolean2);
      assertTrue(boolean5 == boolean3);
      assertFalse(boolean5 == boolean1);
      assertTrue(boolean5 == boolean4);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(boolean5);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertTrue(board0.repOK());
      
      boolean boolean6 = board0.moveLeft();
      assertTrue(boolean6 == boolean3);
      assertTrue(boolean6 == boolean0);
      assertTrue(boolean6 == boolean2);
      assertFalse(boolean6 == boolean1);
      assertTrue(boolean6 == boolean4);
      assertTrue(boolean6 == boolean5);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(boolean6);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertTrue(board0.repOK());
      
      board0.hashCode();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertTrue(board0.repOK());
      
      boolean boolean7 = board0.moveUp();
      assertTrue(boolean7 == boolean5);
      assertTrue(boolean7 == boolean0);
      assertTrue(boolean7 == boolean3);
      assertTrue(boolean7 == boolean6);
      assertTrue(boolean7 == boolean2);
      assertTrue(boolean7 == boolean4);
      assertFalse(boolean7 == boolean1);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(boolean7);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertTrue(board0.repOK());
      
      boolean boolean8 = board0.isLosingBoard();
      assertFalse(boolean8 == boolean5);
      assertFalse(boolean8 == boolean6);
      assertFalse(boolean8 == boolean0);
      assertFalse(boolean8 == boolean3);
      assertFalse(boolean8 == boolean2);
      assertFalse(boolean8 == boolean4);
      assertTrue(boolean8 == boolean1);
      assertFalse(boolean8 == boolean7);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertTrue(boolean8);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertTrue(board0.repOK());
      
      board0.hashCode();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertTrue(board0.repOK());
      
      boolean boolean9 = board0.moveDown();
      assertTrue(boolean9 == boolean6);
      assertFalse(boolean9 == boolean1);
      assertTrue(boolean9 == boolean7);
      assertTrue(boolean9 == boolean0);
      assertTrue(boolean9 == boolean2);
      assertFalse(boolean9 == boolean8);
      assertTrue(boolean9 == boolean3);
      assertTrue(boolean9 == boolean5);
      assertTrue(boolean9 == boolean4);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(boolean9);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertTrue(board0.repOK());
      
      boolean boolean10 = board0.moveUp();
      assertFalse(boolean10 == boolean8);
      assertTrue(boolean10 == boolean0);
      assertTrue(boolean10 == boolean3);
      assertTrue(boolean10 == boolean6);
      assertTrue(boolean10 == boolean5);
      assertTrue(boolean10 == boolean2);
      assertTrue(boolean10 == boolean4);
      assertTrue(boolean10 == boolean9);
      assertFalse(boolean10 == boolean1);
      assertTrue(boolean10 == boolean7);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(boolean10);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertTrue(board0.repOK());
      
      boolean boolean11 = board0.isFull();
      assertFalse(boolean11 == boolean7);
      assertFalse(boolean11 == boolean6);
      assertTrue(boolean11 == boolean1);
      assertTrue(boolean11 == boolean8);
      assertFalse(boolean11 == boolean3);
      assertFalse(boolean11 == boolean4);
      assertFalse(boolean11 == boolean5);
      assertFalse(boolean11 == boolean9);
      assertFalse(boolean11 == boolean0);
      assertFalse(boolean11 == boolean2);
      assertFalse(boolean11 == boolean10);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertTrue(boolean11);
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertTrue(board0.repOK());
      
      // Undeclared exception!
      try { 
        board0.getCell(0, 1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 1) is out of bounds for board size 1
         //
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Board board0 = new Board(11);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(board0);
      assertTrue(board0.repOK());
      assertEquals(0, board0.getScore());
      assertEquals(11, board0.getSize());
      assertFalse(board0.isWinningBoard());
      
      DownMoveStrategy downMoveStrategy0 = new DownMoveStrategy();
      assertNotNull(downMoveStrategy0);
      
      // Undeclared exception!
      board0.move(downMoveStrategy0);
  }

  // FLAKY: depende de las fichas aleatorias.
  @Ignore("Flaky: tablero aleatorio")
  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Board board0 = new Board(1);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(board0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      
      Board board1 = new Board(board0);
      assertTrue(board1.equals((Object)board0));
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(board1);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      assertEquals(0, board1.getScore());
      assertTrue(board1.repOK());
      assertEquals(1, board1.getSize());
      assertFalse(board1.isWinningBoard());
      
      board1.hashCode();
      assertNotSame(board0, board1);
      assertNotSame(board1, board0);
      assertTrue(board0.equals((Object)board1));
      assertTrue(board1.equals((Object)board0));
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      assertEquals(0, board1.getScore());
      assertTrue(board1.repOK());
      assertEquals(1, board1.getSize());
      assertFalse(board1.isWinningBoard());
      
      board1.hashCode();
      assertNotSame(board0, board1);
      assertNotSame(board1, board0);
      assertTrue(board0.equals((Object)board1));
      assertTrue(board1.equals((Object)board0));
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      assertEquals(0, board1.getScore());
      assertTrue(board1.repOK());
      assertEquals(1, board1.getSize());
      assertFalse(board1.isWinningBoard());
      
      boolean boolean0 = board1.moveLeft();
      assertNotSame(board0, board1);
      assertNotSame(board1, board0);
      assertTrue(board0.equals((Object)board1));
      assertTrue(board1.equals((Object)board0));
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertFalse(boolean0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      assertEquals(0, board1.getScore());
      assertTrue(board1.repOK());
      assertEquals(1, board1.getSize());
      assertFalse(board1.isWinningBoard());
      
      Cell cell0 = Cell.EMPTY;
      assertNotNull(cell0);
      assertTrue(cell0.isEmpty());
      assertEquals(".", cell0.toString());
      assertTrue(cell0.repOK());
      assertEquals(0, cell0.getValue());
      
      String string0 = board0.toString();
      assertNotSame(board0, board1);
      assertTrue(board0.equals((Object)board1));
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(string0);
      assertEquals("Score: 0\n+-----+\n|    2|\n+-----+\n", string0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      
      int int0 = board1.getScore();
      assertNotSame(board0, board1);
      assertNotSame(board1, board0);
      assertTrue(board0.equals((Object)board1));
      assertTrue(board1.equals((Object)board0));
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(0, int0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      assertEquals(0, board1.getScore());
      assertTrue(board1.repOK());
      assertEquals(1, board1.getSize());
      assertFalse(board1.isWinningBoard());
      
      boolean boolean1 = board0.isLosingBoard();
      assertNotSame(board0, board1);
      assertTrue(board0.equals((Object)board1));
      assertFalse(boolean1 == boolean0);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertTrue(boolean1);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      
      Cell cell1 = Cell.EMPTY;
      assertSame(cell1, cell0);
      assertNotNull(cell1);
      assertEquals(0, cell1.getValue());
      assertTrue(cell1.repOK());
      assertEquals(".", cell1.toString());
      assertTrue(cell1.isEmpty());
      
      LeftMoveStrategy leftMoveStrategy0 = new LeftMoveStrategy();
      assertNotNull(leftMoveStrategy0);
      
      boolean boolean2 = board1.move(leftMoveStrategy0);
      assertNotSame(board0, board1);
      assertNotSame(board1, board0);
      assertTrue(board0.equals((Object)board1));
      assertTrue(board1.equals((Object)board0));
      assertFalse(boolean2 == boolean1);
      assertTrue(boolean2 == boolean0);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertFalse(boolean2);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      assertEquals(0, board1.getScore());
      assertTrue(board1.repOK());
      assertEquals(1, board1.getSize());
      assertFalse(board1.isWinningBoard());
      
      board0.setCell(0, 0, cell1);
      assertNotSame(board0, board1);
      assertSame(cell1, cell0);
      assertFalse(board0.equals((Object)board1));
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(1, board0.getSize());
      assertEquals(0, board0.getScore());
      assertEquals(0, cell1.getValue());
      assertTrue(cell1.repOK());
      assertEquals(".", cell1.toString());
      assertTrue(cell1.isEmpty());
      
      // Undeclared exception!
      try { 
        Board.Direction.valueOf("+z$n-&n%P<SS");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant ar.edu.unrc.game2048.Board.Direction.+z$n-&n%P<SS
         //
      }
  }

  // FLAKY: depende de las fichas aleatorias.
  @Ignore("Flaky: tablero aleatorio")
  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Board board0 = new Board();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(board0);
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      
      boolean boolean0 = board0.moveUp();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(boolean0);
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      
      String string0 = board0.toString();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(string0);
      assertEquals("Score: 0\n+-----+-----+-----+-----+\n|    2|    2|     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|     |     |     |    2|\n+-----+-----+-----+-----+\n", string0);
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      
      Board.Position board_Position0 = new Board.Position((-1), (-882));
      assertEquals((-1), board_Position0.row);
      assertEquals((-882), board_Position0.col);
      assertNotNull(board_Position0);
      
      String string1 = board_Position0.toString();
      assertFalse(string1.equals((Object)string0));
      assertEquals((-1), board_Position0.row);
      assertEquals((-882), board_Position0.col);
      assertNotNull(string1);
      assertEquals("(-1, -882)", string1);
      
      boolean boolean1 = board0.isLosingBoard();
      assertFalse(boolean1 == boolean0);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertFalse(boolean1);
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      
      String string2 = board_Position0.toString();
      assertTrue(string2.equals((Object)string1));
      assertFalse(string2.equals((Object)string0));
      assertEquals((-1), board_Position0.row);
      assertEquals((-882), board_Position0.col);
      assertNotNull(string2);
      assertEquals("(-1, -882)", string2);
      
      Board.Position board_Position1 = new Board.Position(2048, (-2285));
      assertFalse(board_Position1.equals((Object)board_Position0));
      assertEquals(2048, board_Position1.row);
      assertEquals((-2285), board_Position1.col);
      assertNotNull(board_Position1);
      
      String string3 = board_Position1.toString();
      assertNotSame(board_Position1, board_Position0);
      assertFalse(board_Position1.equals((Object)board_Position0));
      assertFalse(string3.equals((Object)string0));
      assertFalse(string3.equals((Object)string2));
      assertFalse(string3.equals((Object)string1));
      assertEquals(2048, board_Position1.row);
      assertEquals((-2285), board_Position1.col);
      assertNotNull(string3);
      assertEquals("(2048, -2285)", string3);
      
      String string4 = board_Position1.toString();
      assertNotSame(board_Position1, board_Position0);
      assertFalse(board_Position1.equals((Object)board_Position0));
      assertFalse(string4.equals((Object)string2));
      assertFalse(string4.equals((Object)string0));
      assertFalse(string4.equals((Object)string1));
      assertTrue(string4.equals((Object)string3));
      assertEquals(2048, board_Position1.row);
      assertEquals((-2285), board_Position1.col);
      assertNotNull(string4);
      assertEquals("(2048, -2285)", string4);
      
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(set0);
      assertFalse(set0.contains(board_Position1));
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertFalse(set0.isEmpty());
      assertEquals(13, set0.size());
      
      boolean boolean2 = board_Position0.equals(board_Position1);
      assertNotSame(board_Position0, board_Position1);
      assertNotSame(board_Position1, board_Position0);
      assertFalse(board_Position0.equals((Object)board_Position1));
      assertFalse(board_Position1.equals((Object)board_Position0));
      assertFalse(boolean2 == boolean0);
      assertTrue(boolean2 == boolean1);
      assertEquals((-1), board_Position0.row);
      assertEquals((-882), board_Position0.col);
      assertEquals(2048, board_Position1.row);
      assertEquals((-2285), board_Position1.col);
      assertFalse(boolean2);
      
      String string5 = board0.toString();
      assertFalse(string5.equals((Object)string3));
      assertFalse(string5.equals((Object)string2));
      assertFalse(string5.equals((Object)string4));
      assertFalse(string5.equals((Object)string1));
      assertTrue(string5.equals((Object)string0));
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(string5);
      assertEquals("Score: 0\n+-----+-----+-----+-----+\n|    2|    2|     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|     |     |     |    2|\n+-----+-----+-----+-----+\n", string5);
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      
      boolean boolean3 = board0.moveRight();
      assertFalse(boolean3 == boolean2);
      assertTrue(boolean3 == boolean0);
      assertFalse(boolean3 == boolean1);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(boolean3);
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getScore());
      
      int int0 = board0.getScore();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, int0);
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getScore());
      
      boolean boolean4 = board0.repOK();
      assertFalse(boolean4 == boolean2);
      assertTrue(boolean4 == boolean0);
      assertTrue(boolean4 == boolean3);
      assertFalse(boolean4 == boolean1);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(boolean4);
      assertTrue(board0.repOK());
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getScore());
      
      boolean boolean5 = board_Position0.equals(board_Position1);
      assertNotSame(board_Position0, board_Position1);
      assertNotSame(board_Position1, board_Position0);
      assertTrue(boolean5 == boolean2);
      assertFalse(boolean5 == boolean3);
      assertFalse(boolean5 == boolean0);
      assertTrue(boolean5 == boolean1);
      assertFalse(boolean5 == boolean4);
      assertFalse(board_Position0.equals((Object)board_Position1));
      assertFalse(board_Position1.equals((Object)board_Position0));
      assertEquals((-1), board_Position0.row);
      assertEquals((-882), board_Position0.col);
      assertEquals(2048, board_Position1.row);
      assertEquals((-2285), board_Position1.col);
      assertFalse(boolean5);
      
      Cell cell0 = Cell.EMPTY;
      assertNotNull(cell0);
      assertTrue(cell0.repOK());
      assertEquals(".", cell0.toString());
      assertEquals(0, cell0.getValue());
      assertTrue(cell0.isEmpty());
      
      // Undeclared exception!
      try { 
        board0.setCell((-1894), 96, cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-1894, 96) is out of bounds for board size 4
         //
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      int int0 = 25;
      Board board0 = new Board(25);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(board0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(25, board0.getSize());
      assertEquals(0, board0.getScore());
      
      String string0 = board0.toString();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(string0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(25, board0.getSize());
      assertEquals(0, board0.getScore());
      
      // Undeclared exception!
      board0.moveRight();
  }

  // FLAKY: depende de las fichas aleatorias.
  @Ignore("Flaky: tablero aleatorio")
  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Board board0 = new Board();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(board0);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(set0);
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertFalse(set0.isEmpty());
      assertEquals(14, set0.size());
      
      boolean boolean0 = board0.moveLeft();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(boolean0);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getScore());
      
      Cell cell0 = new Cell(2048);
      assertNotNull(cell0);
      assertEquals(2048, cell0.getValue());
      assertFalse(cell0.isEmpty());
      assertEquals("2048", cell0.toString());
      assertTrue(cell0.repOK());
      
      board0.setCell(2, 2, cell0);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertTrue(board0.isWinningBoard());
      assertEquals(4, board0.getScore());
      assertEquals(2048, cell0.getValue());
      assertFalse(cell0.isEmpty());
      assertEquals("2048", cell0.toString());
      assertTrue(cell0.repOK());
      
      boolean boolean1 = board0.isFull();
      assertFalse(boolean1 == boolean0);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertFalse(boolean1);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertTrue(board0.isWinningBoard());
      assertEquals(4, board0.getScore());
      
      boolean boolean2 = board0.isFull();
      assertFalse(boolean2 == boolean0);
      assertTrue(boolean2 == boolean1);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertFalse(boolean2);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertTrue(board0.isWinningBoard());
      assertEquals(4, board0.getScore());
      
      boolean boolean3 = board0.isWinningBoard();
      assertFalse(boolean3 == boolean2);
      assertTrue(boolean3 == boolean0);
      assertFalse(boolean3 == boolean1);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(boolean3);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertTrue(board0.isWinningBoard());
      assertEquals(4, board0.getScore());
      
      board0.hashCode();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertTrue(board0.isWinningBoard());
      assertEquals(4, board0.getScore());
      
      boolean boolean4 = board0.isLosingBoard();
      assertTrue(boolean4 == boolean2);
      assertTrue(boolean4 == boolean1);
      assertFalse(boolean4 == boolean0);
      assertFalse(boolean4 == boolean3);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertFalse(boolean4);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertTrue(board0.isWinningBoard());
      assertEquals(4, board0.getScore());
      
      boolean boolean5 = board0.hasEmptyCells();
      assertFalse(boolean5 == boolean1);
      assertTrue(boolean5 == boolean0);
      assertFalse(boolean5 == boolean2);
      assertFalse(boolean5 == boolean4);
      assertTrue(boolean5 == boolean3);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(boolean5);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertTrue(board0.isWinningBoard());
      assertEquals(4, board0.getScore());
  }

  // FLAKY: depende de las fichas aleatorias.
  @Ignore("Flaky: tablero aleatorio")
  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Board board0 = new Board();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(board0);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      board0.hashCode();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      board0.hashCode();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      boolean boolean0 = board0.moveUp();
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(boolean0);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      boolean boolean1 = board0.moveUp();
      assertTrue(boolean1 == boolean0);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(boolean1);
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      boolean boolean2 = board0.moveUp();
      assertTrue(boolean2 == boolean1);
      assertTrue(boolean2 == boolean0);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(boolean2);
      assertEquals(4, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      
      Board.Direction[] board_DirectionArray0 = Board.Direction.values();
      assertEquals(4, board_DirectionArray0.length);
      assertNotNull(board_DirectionArray0);
      
      UpMoveStrategy upMoveStrategy0 = new UpMoveStrategy();
      assertNotNull(upMoveStrategy0);
      
      List<Cell> list0 = upMoveStrategy0.extractLine(board0, 0);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertNotNull(list0);
      assertEquals(4, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, list0.size());
      assertFalse(list0.isEmpty());
      
      boolean boolean3 = board0.move(upMoveStrategy0);
      assertTrue(boolean3 == boolean1);
      assertTrue(boolean3 == boolean2);
      assertTrue(boolean3 == boolean0);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(2048, Board.WINNING_VALUE);
      assertTrue(boolean3);
      assertEquals(4, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
  }

  // FLAKY: depende de las fichas aleatorias.
  @Ignore("Flaky: tablero aleatorio")
  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(10, 4);
      assertEquals(10, board_Position0.row);
      assertEquals(4, board_Position0.col);
      assertNotNull(board_Position0);
      
      String string0 = board_Position0.toString();
      assertEquals(10, board_Position0.row);
      assertEquals(4, board_Position0.col);
      assertNotNull(string0);
      assertEquals("(10, 4)", string0);
      
      String string1 = board_Position0.toString();
      assertTrue(string1.equals((Object)string0));
      assertEquals(10, board_Position0.row);
      assertEquals(4, board_Position0.col);
      assertNotNull(string1);
      assertEquals("(10, 4)", string1);
      
      String string2 = board_Position0.toString();
      assertTrue(string2.equals((Object)string0));
      assertTrue(string2.equals((Object)string1));
      assertEquals(10, board_Position0.row);
      assertEquals(4, board_Position0.col);
      assertNotNull(string2);
      assertEquals("(10, 4)", string2);
      
      String string3 = board_Position0.toString();
      assertTrue(string3.equals((Object)string2));
      assertTrue(string3.equals((Object)string0));
      assertTrue(string3.equals((Object)string1));
      assertEquals(10, board_Position0.row);
      assertEquals(4, board_Position0.col);
      assertNotNull(string3);
      assertEquals("(10, 4)", string3);
      
      String string4 = board_Position0.toString();
      assertTrue(string4.equals((Object)string0));
      assertTrue(string4.equals((Object)string1));
      assertTrue(string4.equals((Object)string2));
      assertTrue(string4.equals((Object)string3));
      assertEquals(10, board_Position0.row);
      assertEquals(4, board_Position0.col);
      assertNotNull(string4);
      assertEquals("(10, 4)", string4);
      
      boolean boolean0 = board_Position0.equals(board_Position0);
      assertEquals(10, board_Position0.row);
      assertEquals(4, board_Position0.col);
      assertTrue(boolean0);
      
      Board board0 = new Board();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertNotNull(board0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      
      int int0 = board0.getScore();
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(0, int0);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      
      boolean boolean1 = board0.moveRight();
      assertTrue(boolean1 == boolean0);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertTrue(boolean1);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(4, board0.getScore());
      
      boolean boolean2 = board0.isWinningBoard();
      assertFalse(boolean2 == boolean0);
      assertFalse(boolean2 == boolean1);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertFalse(boolean2);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(4, board0.getScore());
      
      int int1 = board0.getSize();
      assertFalse(int1 == int0);
      assertEquals(2048, Board.WINNING_VALUE);
      assertEquals(4, Board.DEFAULT_SIZE);
      assertEquals(4, int1);
      assertTrue(board0.repOK());
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(4, board0.getScore());
      
      // Undeclared exception!
      try { 
        board0.getCell(10, 10);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (10, 10) is out of bounds for board size 4
         //
      }
  }
}
