/*
 * This file was automatically generated by EvoSuite
 * Tue Sep 22 19:53:13 GMT 2026
 */

package ar.edu.unrc.game2048;

import org.junit.Test;
import static org.junit.Assert.*;
import ar.edu.unrc.game2048.Cell;

public class Cell_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      cell0.EMPTY.hashCode();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Cell cell0 = new Cell(1);
      int int0 = cell0.getValue();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Cell cell0 = null;
      try {
        cell0 = new Cell((-1471));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell value cannot be negative: -1471
         //
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Cell cell0 = new Cell(0);
      boolean boolean0 = cell0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals(".", cell0.toString());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Cell cell0 = null;
      try {
        cell0 = new Cell(291);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell value cannot be negative: 291
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Cell cell0 = new Cell(1);
      boolean boolean0 = cell0.canMergeWith(cell0);
      assertTrue(boolean0);
      assertEquals(1, cell0.getValue());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Cell cell0 = new Cell(1);
      Cell cell1 = Cell.EMPTY;
      boolean boolean0 = cell0.canMergeWith(cell1);
      assertEquals("1", cell0.toString());
      assertFalse(cell0.isEmpty());
      assertFalse(boolean0);
      assertTrue(cell1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Cell cell0 = new Cell(1);
      assertFalse(cell0.isEmpty());
      assertEquals("1", cell0.toString());
      
      Cell cell1 = cell0.mergeWith(cell0);
      boolean boolean0 = cell1.canMergeWith(cell0);
      assertFalse(boolean0);
      assertEquals("2", cell1.toString());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Cell cell0 = new Cell(1);
      Cell cell1 = Cell.EMPTY;
      boolean boolean0 = cell1.canMergeWith(cell0);
      assertFalse(boolean0);
      assertTrue(cell1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Cell cell0 = new Cell(1);
      Cell cell1 = Cell.EMPTY;
      // Undeclared exception!
      try { 
        cell0.mergeWith(cell1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot merge cells: 1 and .
         //
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Cell cell0 = new Cell(1);
      assertFalse(cell0.isEmpty());
      
      Cell cell1 = cell0.mergeWith(cell0);
      boolean boolean0 = cell1.equals(cell0);
      assertFalse(cell0.equals((Object)cell1));
      assertFalse(boolean0);
      assertFalse(cell1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Cell cell0 = new Cell(1);
      boolean boolean0 = cell0.equals(cell0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Cell cell0 = new Cell(1);
      boolean boolean0 = cell0.equals("bG|y,h^BBhh2Q^");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Cell cell0 = new Cell(1);
      Cell cell1 = new Cell(1);
      boolean boolean0 = cell0.equals(cell1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Cell cell0 = new Cell(1);
      boolean boolean0 = cell0.isEmpty();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Cell cell0 = new Cell(0);
      boolean boolean0 = cell0.isEmpty();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      boolean boolean0 = cell0.repOK();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Cell cell0 = new Cell(1);
      Cell cell1 = cell0.mergeWith(cell0);
      cell1.repOK();
      assertEquals(2, cell1.getValue());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      String string0 = cell0.toString();
      assertEquals(".", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Cell cell0 = new Cell(1);
      String string0 = cell0.toString();
      assertEquals("1", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Cell cell0 = new Cell(1);
      // Undeclared exception!
      try { 
        cell0.canMergeWith((Cell) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Cell cell0 = new Cell(1);
      // Undeclared exception!
      try { 
        cell0.mergeWith((Cell) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      int int0 = cell0.getValue();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Cell cell0 = new Cell(1);
      Cell cell1 = cell0.mergeWith(cell0);
      // Undeclared exception!
      try { 
        cell0.mergeWith(cell1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot merge cells: 1 and 2
         //
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      Cell cell1 = new Cell(1);
      boolean boolean0 = cell0.equals(cell1);
      assertFalse(boolean0);
      assertFalse(cell1.equals((Object)cell0));
  }
}
